[package]
name = "junction-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
[dependencies]
junction-schema = { path = "../junction-schema" }
serde_json.workspace = true
anyhow.workspace = true
sha2 = "0.10"
[dev-dependencies]
tempfile = "3"
