//! Deterministic Rust/Serde types for selected canonical schemas.
use anyhow::{Result, bail};
use junction_schema::{CanonicalSchema, SchemaType};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};

pub struct RustModule {
    pub source: String,
    /// Canonical reference to generated Rust identifier.
    pub types: BTreeMap<String, String>,
    /// Types using dynamic JSON for composition or unsupported shapes.
    pub dynamic: BTreeSet<String>,
}
/// Generate a standalone module requiring serde and serde_json. Original schema
/// metadata remains available for full constraint validation in Junction.
pub fn generate(schemas: &BTreeMap<String, CanonicalSchema>) -> Result<RustModule> {
    if schemas.is_empty() || schemas.len() > 4096 {
        bail!("invalid generation schema count");
    }
    let types: BTreeMap<_, _> = schemas
        .keys()
        .map(|reference| {
            (
                reference.clone(),
                format!("Schema{:x}", Sha256::digest(reference.as_bytes())),
            )
        })
        .collect();
    let mut state = Generator {
        types: &types,
        declarations: BTreeMap::new(),
        dynamic: BTreeSet::new(),
        nodes: 0,
    };
    for (reference, schema) in schemas {
        state.emit(&types[reference], &schema.schema_type, 0)?;
    }
    let metadata = serde_json::to_string(schemas)?;
    if metadata.len() > 128 * 1024 * 1024 {
        bail!("generation metadata limit exceeded");
    }
    let mut source = String::from(
        "// Generated by Junction; validate full constraints against SCHEMAS_JSON.\n#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n#[serde(untagged)]\npub enum Nullable<T> { Null(()), Value(T) }\nfn present<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error> where D: serde::Deserializer<'de>, T: serde::Deserialize<'de> { T::deserialize(deserializer).map(Some) }\n",
    );
    source.push_str(&format!("pub const SCHEMAS_JSON: &str = {metadata:?};\n"));
    for declaration in state.declarations.values() {
        source.push_str(declaration);
    }
    if source.len() > 256 * 1024 * 1024 {
        bail!("generated source limit exceeded");
    }
    Ok(RustModule {
        source,
        types: types.clone(),
        dynamic: state.dynamic,
    })
}
struct Generator<'a> {
    types: &'a BTreeMap<String, String>,
    declarations: BTreeMap<String, String>,
    dynamic: BTreeSet<String>,
    nodes: usize,
}
impl Generator<'_> {
    fn expression(&mut self, name: &str, schema: &SchemaType, depth: usize) -> Result<String> {
        self.nodes += 1;
        if depth > 128 || self.nodes > 100_000 {
            bail!("generation traversal limit exceeded");
        }
        Ok(match schema {
            SchemaType::String { .. } => "String".into(),
            SchemaType::Integer { format } => if format.as_deref() == Some("uint64") {
                "u64"
            } else {
                "i64"
            }
            .into(),
            SchemaType::Number { .. } => "f64".into(),
            SchemaType::Boolean => "bool".into(),
            SchemaType::Null => "()".into(),
            SchemaType::Reference { target } => format!(
                "Box<{}>",
                self.types
                    .get(target)
                    .ok_or_else(|| anyhow::anyhow!("generation requires reference closure"))?
            ),
            SchemaType::Nullable { value } => format!(
                "Nullable<{}>",
                self.expression(&format!("{name}Value"), value, depth + 1)?
            ),
            SchemaType::Array { items } => format!(
                "Vec<{}>",
                self.expression(&format!("{name}Item"), items, depth + 1)?
            ),
            SchemaType::Union {
                variants,
                discriminator: None,
                ..
            } if variants.len() == 2
                && variants
                    .iter()
                    .filter(|variant| matches!(variant, SchemaType::Null))
                    .count()
                    == 1 =>
            {
                let value = variants
                    .iter()
                    .find(|variant| !matches!(variant, SchemaType::Null))
                    .unwrap();
                format!(
                    "Nullable<{}>",
                    self.expression(&format!("{name}Value"), value, depth + 1)?
                )
            }
            SchemaType::Object { .. } | SchemaType::Enum { .. } => {
                self.emit(name, schema, depth + 1)?;
                name.into()
            }
            _ => {
                self.dynamic.insert(name.into());
                "serde_json::Value".into()
            }
        })
    }
    fn emit(&mut self, name: &str, schema: &SchemaType, depth: usize) -> Result<()> {
        let derive = "#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n";
        let declaration = match schema {
            SchemaType::Object {
                properties,
                additional,
            } => {
                let mut output = derive.to_owned();
                if matches!(additional.as_ref(), SchemaType::Never) {
                    output.push_str("#[serde(deny_unknown_fields)]\n");
                }
                output.push_str(&format!("pub struct {name} {{\n"));
                for (index, (property, value)) in properties.iter().enumerate() {
                    let ty =
                        self.expression(&format!("{name}Field{index}"), &value.schema, depth + 1)?;
                    let rename = format!("{property:?}");
                    if value.required {
                        output.push_str(&format!(
                            "#[serde(rename = {rename})]\npub field_{index}: {ty},\n"
                        ));
                    } else {
                        output.push_str(&format!("#[serde(rename = {rename}, default, deserialize_with = \"present\", skip_serializing_if = \"Option::is_none\")]\npub field_{index}: Option<{ty}>,\n"));
                    }
                }
                if !matches!(additional.as_ref(), SchemaType::Never) {
                    let ty =
                        self.expression(&format!("{name}Additional"), additional, depth + 1)?;
                    output.push_str(&format!("#[serde(flatten)]\npub additional: std::collections::BTreeMap<String, {ty}>,\n"));
                }
                output.push_str("}\n");
                output
            }
            SchemaType::Enum { values, .. }
                if !values.is_empty() && values.iter().all(serde_json::Value::is_string) =>
            {
                let mut output = format!("{derive}pub enum {name} {{\n");
                for (index, value) in values.iter().enumerate() {
                    output.push_str(&format!(
                        "#[serde(rename = {:?})]\nVariant{index},\n",
                        value.as_str().unwrap()
                    ));
                }
                output.push_str("}\n");
                output
            }
            SchemaType::Enum { .. } => {
                self.dynamic.insert(name.into());
                format!("{derive}pub struct {name}(pub serde_json::Value);\n")
            }
            _ => {
                let ty = self.expression(&format!("{name}Inner"), schema, depth + 1)?;
                format!("{derive}pub struct {name}(pub {ty});\n")
            }
        };
        if self.declarations.insert(name.into(), declaration).is_some() {
            bail!("generated identifier collision");
        }
        Ok(())
    }
}

/// Select named schemas and their complete local reference closure.
pub fn generate_selected(
    schemas: &BTreeMap<String, CanonicalSchema>,
    roots: &[String],
) -> Result<RustModule> {
    if roots.is_empty() || roots.len() > 256 {
        bail!("invalid generation selection count");
    }
    let mut selected = BTreeMap::new();
    let mut pending: BTreeSet<String> = roots.iter().cloned().collect();
    while let Some(reference) = pending.pop_first() {
        if selected.contains_key(&reference) {
            continue;
        }
        if selected.len() >= 4096 {
            bail!("generation reference closure limit exceeded");
        }
        let schema = schemas
            .get(&reference)
            .ok_or_else(|| anyhow::anyhow!("generation schema not found"))?;
        collect(&schema.schema_type, &mut pending, 0)?;
        selected.insert(reference, schema.clone());
    }
    generate(&selected)
}
fn collect(schema: &SchemaType, references: &mut BTreeSet<String>, depth: usize) -> Result<()> {
    if depth > 128 {
        bail!("generation traversal limit exceeded");
    }
    match schema {
        SchemaType::Reference { target } => {
            references.insert(target.clone());
        }
        SchemaType::Nullable { value }
        | SchemaType::Array { items: value }
        | SchemaType::Enum {
            underlying: value, ..
        } => collect(value, references, depth + 1)?,
        SchemaType::Object {
            properties,
            additional,
        } => {
            for property in properties.values() {
                collect(&property.schema, references, depth + 1)?;
            }
            collect(additional, references, depth + 1)?;
        }
        SchemaType::Union {
            variants: members, ..
        }
        | SchemaType::Intersection { members } => {
            for member in members {
                collect(member, references, depth + 1)?;
            }
        }
        _ => {}
    }
    Ok(())
}
